"""baseline schema

Revision ID: 2cb1b34122f6
Revises: 
Create Date: 2026-06-27 00:05:56.038449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb1b34122f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_company'), ['company'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('influencer_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_logs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_logs_id'), ['id'], unique=False)

    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_email', sa.String(length=160), nullable=False),
    sa.Column('owner_name', sa.String(length=160), nullable=False),
    sa.Column('client_name', sa.String(length=160), nullable=False),
    sa.Column('campaign_name', sa.String(length=200), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('responsible_member_id', sa.Integer(), nullable=True),
    sa.Column('responsible_member_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('period_start', sa.String(length=40), nullable=False),
    sa.Column('period_end', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('stakeholders', sa.Text(), nullable=False),
    sa.Column('drive_folder_url', sa.Text(), nullable=False),
    sa.Column('input_files', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('influencer_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('kols', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('sow_options', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('assigned_user_ids', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('budget_show', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_assets_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_campaign_name'), ['campaign_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_client_name'), ['client_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_responsible_member_id'), ['responsible_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_assets_status'), ['status'], unique=False)

    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('section_a', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('section_b', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_briefs_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_briefs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_briefs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_briefs_title'), ['title'], unique=False)

    op.create_table('influencers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('active_since', sa.String(length=20), nullable=False),
    sa.Column('niche', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('social_links', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('growth_30d', sa.Float(), nullable=False),
    sa.Column('platforms', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('code_gen_fee', sa.Float(), nullable=False),
    sa.Column('management_fee', sa.Float(), nullable=False),
    sa.Column('agency_fee_pct', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('brand_safety', sa.Float(), nullable=False),
    sa.Column('audience_alignment', sa.Float(), nullable=False),
    sa.Column('content_quality', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('fit_note', sa.Text(), nullable=False),
    sa.Column('scope_of_work', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('past_campaigns', sa.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_influencers_handle'), ['handle'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_niche'), ['niche'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_influencers_tier'), ['tier'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_role'), ['role'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=160), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_role'))
        batch_op.drop_index(batch_op.f('ix_members_name'))
        batch_op.drop_index(batch_op.f('ix_members_id'))
        batch_op.drop_index(batch_op.f('ix_members_email'))

    op.drop_table('members')
    with op.batch_alter_table('influencers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_influencers_tier'))
        batch_op.drop_index(batch_op.f('ix_influencers_platform'))
        batch_op.drop_index(batch_op.f('ix_influencers_niche'))
        batch_op.drop_index(batch_op.f('ix_influencers_name'))
        batch_op.drop_index(batch_op.f('ix_influencers_id'))
        batch_op.drop_index(batch_op.f('ix_influencers_handle'))

    op.drop_table('influencers')
    with op.batch_alter_table('content_briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_briefs_title'))
        batch_op.drop_index(batch_op.f('ix_content_briefs_status'))
        batch_op.drop_index(batch_op.f('ix_content_briefs_id'))
        batch_op.drop_index(batch_op.f('ix_content_briefs_campaign_id'))

    op.drop_table('content_briefs')
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_assets_status'))
        batch_op.drop_index(batch_op.f('ix_content_assets_responsible_member_id'))
        batch_op.drop_index(batch_op.f('ix_content_assets_owner_email'))
        batch_op.drop_index(batch_op.f('ix_content_assets_id'))
        batch_op.drop_index(batch_op.f('ix_content_assets_client_name'))
        batch_op.drop_index(batch_op.f('ix_content_assets_campaign_name'))
        batch_op.drop_index(batch_op.f('ix_content_assets_brand_id'))

    op.drop_table('content_assets')
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_logs_id'))
        batch_op.drop_index(batch_op.f('ix_change_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_change_logs_asset_id'))

    op.drop_table('change_logs')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_brand'))

    op.drop_table('campaigns')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))
        batch_op.drop_index(batch_op.f('ix_brands_id'))
        batch_op.drop_index(batch_op.f('ix_brands_company'))

    op.drop_table('brands')
    # ### end Alembic commands ###
