"""audit log: entity, actor_id, detail

Revision ID: a064967d4ce8
Revises: d7c747274490
Create Date: 2026-06-27 21:08:30.589325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a064967d4ce8'
down_revision: Union[str, Sequence[str], None] = 'd7c747274490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity', sa.String(length=20), server_default=sa.text("'campaign'"), nullable=False))
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detail', sa.JSON(), nullable=True))
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_change_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_logs_entity'), ['entity'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_change_logs_actor_id'))
        batch_op.alter_column('asset_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('detail')
        batch_op.drop_column('actor_id')
        batch_op.drop_column('entity')

    # ### end Alembic commands ###
