"""add content_asset.row_version

Revision ID: d7c747274490
Revises: 16bfedc00dad
Create Date: 2026-06-27 16:04:56.980567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c747274490'
down_revision: Union[str, Sequence[str], None] = '16bfedc00dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_version', sa.Integer(), server_default=sa.text('1'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_assets', schema=None) as batch_op:
        batch_op.drop_column('row_version')

    # ### end Alembic commands ###
